config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users
  root 'items#index'
  
  resources :users , only:[:index] do
    collection do
      get :logout 
      get :creditcard
    end
  end

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get :purchase
    end
    collection do
      get :category
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :card
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :family_name, presence: true, format: { with:/\A[ぁ-んァ-ン一-龥]/}
  validates :first_name, presence: true, format: { with:/\A[ぁ-んァ-ン一-龥]/}
  validates :family_name_kana, presence: true, format: { with:/\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: { with:/\A[ァ-ヶー－]+\z/}
  validates :birth_year, presence: true, format: { with:/\A[0-9]+\z/}
  validates :d_family_name, presence: true, format: { with:/\A[ぁ-んァ-ン一-龥]/}
  validates :d_first_name, presence: true, format: { with:/\A[ぁ-んァ-ン一-龥]/}
  validates :d_family_name_kana, presence: true, format: { with:/\A[ァ-ヶー－]+\z/}
  validates :d_first_name_kana, presence: true, format: { with:/\A[ァ-ヶー－]+\z/}
  validates :zip_code, presence: true, format: { with:/\A\d{7}\z/}
  validates :prefecture, presence: true, format: {with:/\A[一-龥]+\z/}
  validates :city, presence: true, format: { with:/\A[一-龥]+\z/}
  validates :password, length: { minimum: 7 }
  validates :address, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def creditcard
    render "users/creditcard"
  end

  def index
    @nickname = current_user.nickname
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/creditcard.html.haml
.wrapper
  = render "items/header"
  .main
    .content
      .content__left
        .content__left__mypage
          %h2.mypage-head 設定
          .content__left__mypage__list
            .content__left__mypage__list__item
              =link_to "クレジットカード登録", creditcard_users_path, method: :get
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "ログアウト", logout_users_path, method: :get
      .content__right3
        .content__right3__card
          .content__right3__card__headcolor
            %h2.content__right3__card__headcolor__text クレジットカード情報入力
          .content__right3__card__registrationform
            = form_with local: :true do |form|
              .content__right3__card__registrationform__content
                .content__right3__card__registrationform__content__formgroup1
                  = form.label :カード番号, class: 'payment_card_no'
                  %span.form-require 必須
                  = form.text_field :name, class: 'payment_card_no1', placeholder: '半角数字のみ'

                  %ul#card-no-error-wrapper.has-error-text
                  %ul.signup-card-list
                    %li
                    = image_tag "logo.png", height: "20px"
                    %li
                    = image_tag "logo.png", height: "20px"
                    %li
                    = image_tag "logo.png", height: "20px"
                .content__right3__card__registrationform__content__formgroup2
                  = form.label :有効期限, class: 'payment_card_no'
                  %span.form-require 必須
                  = form.text_field :name, class: 'payment_card_no2', placeholder: '月/年を入力してください' 

                .content__right3__card__registrationform__content__formgroup3
                  = form.label :セキュリティコード, class: 'payment_card_no'
                  %span.form-require 必須
                  = form.text_field :name, class: 'payment_card_no3', placeholder: 'カード背面4桁もしくは3桁の番号'
                
                .content__right3__card__registrationform__content__formgroup4
                  =link_to "登録する", destroy_user_session_path, method: :delete
  =render "items/footer"

app/views/users/index.html.haml
.wrapper
  = render "items/header"
  .main
    .content
      .content__left
        .content__left__mypage
          %h2.mypage-head 設定
          .content__left__mypage__list
            .content__left__mypage__list__item
              =link_to "クレジットカード登録", new_card_path, method: :get
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "ログアウト", logout_users_path
      .content__right
        .content__right__mypageicon
          %figure
            = image_tag "member_photo_noimage_thumb.png", height: "49px", width:"50%"   
          %h5.bold
            = @nickname
        .content__right__mypagebuy
          %ul.content__right__mypagebuy__tabs
            %li.content__right__mypagebuy__tabs__left
              %h4
                =link_to "取引中", "#", class:"rightlink"
            %li.content__right__mypagebuy__tabs__right
              %h4
                =link_to "過去の取引", "#", class:"rightlink"
          .content__right__mypagebuy__tabcontent
            %ul.content__right__mypagebuy__tabcontent__contents
              %li 取引中の商品がありません
            %ul.content__right__mypagebuy__tabcontent__contents
              %li 過去に取引した商品がありません
  =render "items/footer"

app/views/users/logout.html.haml
.wrapper
  = render "items/header"
  .main
    .content
      .content__left
        .content__left__mypage
          %h2.mypage-head 設定
          .content__left__mypage__list
            .content__left__mypage__list__item
              =link_to "クレジットカード登録", creditcard_users_path, method: :get
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "ログアウト", logout_users_path, method: :get
      .content__right2
        .content__right2__btn
          %form.content__right2__btn__inner{:action => "https://www.mercari.com/jp/logout/", :method => "POST", :novalidate => "novalidate"}
            .content__right2__btn__inner__content
              =link_to "ログアウト", destroy_user_session_path, method: :delete 
  =render "items/footer"