config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users
  root 'items#index'
  
  resources :users , only:[:index] do
    collection do
      get :logout 
      get :creditcard
    end
  end

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get :purchase
    end
    collection do
      get :category
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  #アソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :deliveryfeeburgen
  belongs_to_active_hash :deliveryservice
  belongs_to_active_hash :deliveryarea
  belongs_to_active_hash :deliveryhandlingtime
  belongs_to_active_hash :itemcondition

  belongs_to :category

  # belongs_to :brand, optional: true 
  belongs_to :user
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  has_one :shipping, dependent: :destroy
  accepts_nested_attributes_for :shipping
  


  #バリデーション
  validates :item_images, presence: true, length: { minimum: 1, maximum: 4 }
  validates :name, presence: true, length: { maximum: 40 }
  validates :i_text, presence: true, length: { maximum: 1000 }
  # validates :category_id, presence: true
  validates :condition_id, presence: true
  validates :price, presence: true, inclusion: 300..9999999

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_item, only: [:show, :edit,:update,:destroy]

  def index
    @items = Item.includes(:item_images).order('created_at DESC')
    @item_images = ItemImage.new
  end

  def new
    @item = Item.new
    @item.build_shipping
    @item.item_images.build

    category_parent_array = ["---"]  
    category_parent_array << Category.where(ancestry: nil).pluck(:name)
    @category_parent_array = category_parent_array.flatten
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    #出品中
    @item.trading_status = 0
    if @item.save
      redirect_to root_path
    else
      category_parent_array = ["---"]  
      category_parent_array << Category.where(ancestry: nil).pluck(:name)
      @category_parent_array = category_parent_array.flatten
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
    @item_images = ItemImage.new
  end

  def edit
    category_parent_array = ["---"]  
    category_parent_array << Category.where(ancestry: nil).pluck(:name)
    @category_parent_array = category_parent_array.flatten

    grandchild_category = @item.category
    child_category = grandchild_category.parent

    # 既にある情報を持ってくる
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end
    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end
  

  def update
    if @item.update(item_params)
      redirect_to action: "index"
    else
      category_parent_array = ["---"]  
      category_parent_array << Category.where(ancestry: nil).pluck(:name)
      @category_parent_array = category_parent_array.flatten
      grandchild_category = @item.category
      child_category = grandchild_category.parent
      # 既に入力されている情報を持ってくる
      @category_parent_array = []
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      @category_children_array = []
      Category.where(ancestry: child_category.ancestry).each do |children|
        @category_children_array << children
      end
      @category_grandchildren_array = []
      Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
        @category_grandchildren_array << grandchildren
      end

      render :action => "edit"    
    end  
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  def category
    @children = Category.find(params[:parent_id]).children
      respond_to do |format|
        format.html
        format.json
      end
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :i_text, :condition_id, :category_id, :brand_id, :price, shipping_attributes: [:id,:fee_burgen_id, :service_id, :area_id, :handling_time_id], item_images_attributes: [:id,:image_url,:_destroy]).merge(user_id: current_user.id)
  end
  
  def set_item
    @item=Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error-messages.html.haml
- if @item.errors.any?
  -# エラーがあるフォームだけ実行
  - unless @item.valid?
    #error_explanation.alert.alert-danger
      %ul.item-error-text
        - @item.errors.full_messages.each do |message|
          %li= message

-# - if product.errors.any?
-#   - unless product.valid?
-#     - if errors = product.errors.full_messages_for(column.to_sym)
-#       %ul
-#         - errors.each do |error|
-#           %li=error

-# - if @item.errors.any?
-#   #error_explanation.alert.alert-danger
-#     %ul
-#       - @item.errors.full_messages.each do |message|
-#         %li= message

app/views/items/_footer.html.haml
.appBanner
  .inner
    %h2.inner__title だれでも簡単、人生を変えるフリマアプリ
    %p.inner__text 今すぐ無料ダウンロード！
    .inner__icon
      = link_to "/", target: "_self" do
        = image_tag "logo/download-on-the-app-store-apple.svg", class:"apple--logo"
      = link_to "/", target: "_self" do
        = image_tag "logo/google-play-badge.svg", class:"google--logo"
  =image_tag 'pict/bg-appBanner-pict.jpg'
.footer--contents
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul.lists
        %li.list
          = link_to "会社概要（運営会社）", "#", class: "link"
        %li.list
          = link_to "プライバシーポリシー", "#", class: "link"
        %li.list
          = link_to "FURIMA利用規約", "#", class: "link"
        %li.list
          = link_to "ポイントに関する特約", "#", class: "link"
    %li.content
      %h2.content__head FURIMAを見る
      %ul.lists
        %li.list
          = link_to "カテゴリー一覧", "#", class: "link"
        %li.list
          = link_to "ブランド一覧", "#", class: "link"
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul.lists
        %li.list
          = link_to "FURIMAガイド", "#", class: "link"
        %li.list
          = link_to "FURIMAロゴ利用ガイドライン", "#", class: "link"
        %li.list
          = link_to "お知らせ", "#", class: "link"
  .footer--logo
    = link_to "/", target: "_self" do
      = image_tag "logo/logo-white.png", class:"white--logo"
    %p ©︎ FURIMA
-# = link_to '出品', new_product_path
-# %br
-# .contents
-#   = render @products
- if user_signed_in?
  = link_to "/items/new" do
    .sell-btn
      %span.sell-btn__text
        出品する
      = image_tag 'icon/icon_camera.png',class:"sell-btn__icon"

app/views/items/_form.html.haml
%script{:src => "new_category.js"}

.item-new-header
  .item-new-header__logo
    = link_to root_path do
      = image_tag "logo.png", width: "170px", height: "50px", class: "item-new-header__logo__image"
= render partial: 'error-messages', locals: { item: @item.errors, column: 'name'}
.item-new-main
  .item-new-main__wrapper
    .item-new-contents
      = form_with model: @item, local: true do |form|
        / 画像
        .item-new-images
          .item-new-images__block
            .item-new-images__block__label
              %label.item-new-images__block__label__title 出品画像
              %span.item-new-form 必須
            %p.item-new-label 最大4枚までアップロード可能
            / 画像4枚挿入
            .item-new-images__block__container#image-box-1
              #image-box
                #previews
                  - if @item.persisted?
                    - @item.item_images.each_with_index do |image, i|
                      = image_tag image.image_url.url, data: { index: i }, width: "100", height: '100'
                = form.fields_for :item_images do |image|
                  .js-file_group{"data-index" => image.index}
                    = image.file_field :image_url, class: 'js-file'
                    %br/
                    %span.js-remove 削除
                  - if @item.persisted?
                    = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                - if @item.persisted?
                  .js-file_group{"data-index" => @item.item_images.count}
                    = file_field_tag :image_url, name: "item[item_images_attributes][#{@item.item_images.count}][image_url]", class: 'js-file'
                    .js-remove 削除
        / 商品の概要
        .item-new-overview
          .item-new-overview__block
            %p.item-new-label 商品の概要
            / 商品名
            .item-new-overview__block__name
              .item-new-overview__block__name__label
                %label.item-new-overview__block__name__label__title 商品名
                %span.item-new-form 必須
              = form.text_field :name, placeholder: "商品名(40文字まで)", class: "item-new-overview__block__name__content"
            / 商品の説明
            .item-new-overview__block__message
              .item-new-overview__block__message__label
                %label.item-new-overview__block__message__label__title 商品の説明
                %span.item-new-form 必須
              = form.text_area :i_text, placeholder: "商品の説明(1,000文字以内)\n色、素材、重さ、定価、注意点など", class: "item-new-overview__block__message__content"
            / カテゴリー
            .item-new-overview__block__category
              .item-new-overview__block__category__label
                %label.item-new-overview__block__category__label__title カテゴリー
                %span.item-new-overview__block__category__label__required.item-new-form 必須
                //- binding.pry
              = form.select :category, @category_parent_array, {},{class: 'item-new-overview__block__category__content', id: 'parent_category'}
              %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down

            / ブランド
            .item-new-overview__block__brand
              .item-new-overview__block__brand__label
                %label.item-new-overview__block__brand__label__title ブランド
              = form.text_field :brand_id, placeholder: "ブランド", class: "item-new-overview__block__brand__content"
            / 商品の状態
            .item-new-overview__block__select
              .item-new-overview__block__select__label
                %label.item-new-overview__block__select__label__title 商品の状態
                %span.item-new-overview__block__select__label__required.item-new-form 必須
              = form.collection_select :condition_id, Itemcondition.all, :id, :value, {prompt: "選択してください"}, class: "item-new-overview__block__select__content"
        / 配送について===================================
        .item-new-delivery
          = form.fields_for :shipping, local: true do |i|
            .item-new-delivery__block
              %p.item-new-label 配送について
              / 配送料の負担
              .item-new-delivery__block__select
                .item-new-delivery__block__select__label
                  %label.item-new-delivery__block__select__label__title 配送料の負担
                  %span.item-new-delivery__block__select__label__required.item-new-form 必須
                = i.collection_select :fee_burgen_id, Deliveryfeeburgen.all, :id, :value, {prompt: "選択してください"}, class: "item-new-overview__block__select__content"
              / 配送方法
              .item-new-delivery__block__select
                .item-new-delivery__block__select__label
                  %label.item-new-delivery__block__select__label__title 配送方法
                  %span.item-new-delivery__block__select__label__required.item-new-form 必須
                = i.collection_select :service_id, Deliveryservice.all, :id, :value, {prompt: "選択してください"}, class: "item-new-overview__block__select__content"
              / 発送元の地域
              .item-new-delivery__block__select
                .item-new-delivery__block__select__label
                  %label.item-new-delivery__block__select__label__title 発送元の地域
                  %span.item-new-delivery__block__select__label__required.item-new-form 必須
                = i.collection_select :area_id, Deliveryarea.all, :id, :name, {prompt: "選択してください"}, class: "item-new-delivery__block__select__content"
              / 発送日数
              .item-new-delivery__block__select
                .item-new-delivery__block__select__label
                  %label.item-new-delivery__block__select__label__title 発送日数
                  %span.item-new-delivery__block__select__label__required.item-new-form 必須
                = i.collection_select :handling_time_id, Deliveryhandlingtime.all, :id, :value, {prompt: "選択してください"}, class: "item-new-delivery__block__select__content"
        / 価格==================================================
        .item-new-price
          .item-new-price__block
            %p.item-new-label 価格(¥300〜9,999,999)
            / 販売価格
            .item-new-price__block__selling
              .item-new-price__block__selling__label
                %label.item-new-price__block__selling__label__title 販売価格
                %span.item-new-price__block__selling__label__required.item-new-form 必須
              .item-new-price__block__selling__content 
                %span.item-new-price-fee ¥
                = form.text_field :price, placeholder: "〜9,999,999", class: "item-new-price__block__selling__content__input"
            / 販売手数料
            .item-new-price__block__committion
              .item-new-price__block__committion__label
                %label.item-new-price__block__committion__label__title 販売手数料
              .item-new-price__block__committion__content
              %span.item-new-price-fee ¥--
              / 自動計算 手数料10%
            / 販売利益
            .item-new-price__block__profit
              .item-new-price__block__profit__label
                %label.item-new-price__block__profit__label__title 販売利益
              .item-new-price__block__profit__content
              %span.item-new-price-fee ¥--
              / 販売利益 算出
            / ボタン
            .item-new-btn-content
              - if @item.persisted?
                = form.submit "変更する",  class:"item-new-btn-content__form"
              - else
                = form.submit "出品する",  class:"item-new-btn-content__form"

.item-new-footer
  .item-new-footer__logo
    = link_to items_path do
      = image_tag "logo-white.png", width: "170px", height: "50px", class: "item-new-footer__logo__image"
    %p.item-new-footer__logo__copyright © FURIMA

app/views/items/_header.html.haml
.headers
  .header
    .main
      .main__img
        = link_to '/',target: "_self" do
          = image_tag 'logo/logo.png', class:'input-text'
      .main__search
        = form_with url:"root_path" do|form|
          = form.text_field :text, class:"text", placeholder: "キーワードから探す"
          = button_tag type:"submit", class:"input" do
            %i.fas.fa-search.fa-2x
    .box
      %ul.box__left
        %li.box__left__categories
          = link_to "カテゴリー", "#", class: "category_title", id: "category_title_id"
          .category_inner_list
            %ul.parents_list
              - @parents.each do |parent|
                %li 
                = link_to "#{parent.name}", items_path(parent), class: "parent_category",id: "#{parent.id}"
            %ul.children_list
            %ul.grand_children_list
        %li.box__left__brand
          = link_to 'ブランド','/'
      .box__right
        - if user_signed_in?
          %li.box__right__login
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          %li.box__right__new
            = link_to 'マイページ', users_path
        - else
          %li.box__right__login
            = link_to "ログイン", new_user_session_path
          %li.box__right__new
            = link_to "新規登録", new_user_registration_path
        

app/views/items/index.html.erb
<h1>Items#index</h1>
Freemarket Sample
Freemarket Sample
Freemarket Sample
Freemarket Sample
Freemarket Sample
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/index.html.haml
%script{src: "index_category.js"}
.wrapper
  = render "header"
  .main
    .mainvalu
      .mainvalu__content
        .mainvalu__content__title
          %br 人生を変えるフリマアプリ
        %p.mainvalu__content__text
          FURIMAはだれでもかんたんに出品・購入できる
          %br フリマアプリです
        %p.mainvalu__content__btn
          = link_to "/", target: "_self" do
            = image_tag "logo/download-on-the-app-store-apple.svg", class:"apple--logo"
          = link_to "/", target: "_self" do
            = image_tag "logo/google-play-badge.svg", class:"google--logo"
      = image_tag 'pict/bg-mainVisual-pict_pc.jpg'
    .topintoroduction
      .title
        FURIMAが選ばれる3つの理由
      .lists
        %li.list
          .list__pick
            %span.number
              1
            = image_tag 'pict/pict-reason-01.jpg', class: 'img'
          %h3.list__text
            %span
              3分
            ですぐに出品
          %p.list__desc
            スマホで入力するだけで簡単に出品できる！
        %li.list
          .list__pick
            %span.number
              2
            = image_tag 'pict/pict-reason-02.jpg', class: 'img'
          %h3.list__text
            %span
              シンプル
            で使いやすい
          %p.list__desc
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.list.list--last
          .list__pick
            %span.number
              3
            = image_tag 'pict/pict-reason-03.jpg', class: 'img'
          %h3.list__text
            手数料
            %span
              業界最安
          %p.list__desc
          最大3%でお得に出品&購入！
    .topmid
      .topmid__inner
        %h2.title
          会員数日本一位
        %p.text
          FURIMAは、フリマアプリで最も人気。
          %br
            出品・購入回数も業界最多です！
          %br
            ほしかったあの商品に出会えるかもしれません。
        .btn
          = link_to "/", target: "_self" do
            = image_tag "logo/download-on-the-app-store-apple.svg", class:"apple--logo"
          = link_to "/", target: "_self" do
            = image_tag "logo/google-play-badge.svg", class:"google--logo"
      = image_tag 'pict/bg-topMiddleDl-pict.jpg'
    .topkey
      %h2.head
        FURIMAの特徴
      .items
        .item
          %li.item__img
            = image_tag "icon/icon-01.png",class:"image"
          %h3.item__title
            簡単に売り買いできる
          %p.item__detail
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        .item
          %li.item__img
            = image_tag "icon/icon-03.png",class:"image"
          %h3.item__title
            売上金は即日振込みに対応
          %p.item__detail
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        .item
          %li.item__img
            = image_tag "icon/icon-04.png",class:"image"
          %h3.item__title
            様々な支払いに対応
          %p.item__detail
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    .picupContainer
      %h2.head ピックアップカテゴリー
      .productBox
        .productHead
          -# 仮で商品詳細ページにリンクしてます
          = link_to "#" do
            = ""
            %h3.title 新規投稿商品
        .productLists
          - @items.first(3).each do |item|
            .productList 
              -if item.trading_status == 0
                = link_to (item_path(item.id)) do
                  %figure.productList--img
                    =image_tag("#{item.item_images[0].image_url}", class:"image")
                  .productList--body
                    %h3.name 
                    = item.name
                    .details
                      %ul
                        %li 
                        = item.price
                        円
                        %li
                          %i.fa.fa-star.likeIcon
                            = 0
                      %p （税込）
              -if item.trading_status == 1
                = link_to ("#") do
                  %figure.productList--img
                    =image_tag("#{item.item_images[0].image_url}", class:"image")
                    .productList--red
                    .productList--sold
                      SOLD   
                  .productList--body
                    %h3.name 
                    = item.name
                    .details
                      %ul
                        %li 
                        = item.price
                        円
                        %li
                          %i.fa.fa-star.likeIcon
                            = 0
                      %p （税込）
    .picupContainer
      %h2.head ピックアップブランド
      .productBox
        .productHead
          = link_to "/" do
            = ""
            %h3.title アーカイバ
        .productLists
          - @items.first(3).each do |item|
            .productList 
              -if item.trading_status == 0
                = link_to (item_path(item.id)) do
                  %figure.productList--img
                    =image_tag("#{item.item_images[0].image_url}", class:"image")
                  .productList--body
                    %h3.name 
                    = item.name
                    .details
                      %ul
                        %li 
                        = item.price
                        円
                        %li
                          %i.fa.fa-star.likeIcon
                            = 0
                      %p （税込）
              -if item.trading_status == 1
                = link_to ("#") do
                  %figure.productList--img
                    =image_tag("#{item.item_images[0].image_url}", class:"image")
                    .productList--red
                    .productList--sold
                      SOLD   
                  .productList--body
                    %h3.name 
                    = item.name
                    .details
                      %ul
                        %li 
                        = item.price
                        円
                        %li
                          %i.fa.fa-star.likeIcon
                            = 0
                      %p （税込）
          
  = render "footer"
  = link_to new_item_path do
    .sell-btn
      %span.sell-btn__text
        出品する
      = image_tag 'icon/icon_camera.png',class:"sell-btn__icon"

app/views/items/purchase.html.haml
.a--body
  .a--container
    %header.a--header
      %h1
        = link_to "#" do
          = image_tag "logo/logo.png", class:"furima--logo"
    %main.a--main
      .a--main__container
        %h2.a--main__container__head 購入内容の確認
        .buy--content
          .buy--content__inner
            .buy--content__inner__item
              %h3.buy--content__inner__item__image
                = image_tag "pict/food_rakusa_laksa_ra-men.png", class:"a-image"
              .buy--content__inner__item__detail
                %p.buy--content__inner__item__detail__name ラーメン
                %p.buy--content__inner__item__detail__price
                  %span ¥10,000
                  %span.item--shipping--fee（税込）送料込み
        .buy--content
          .buy--content__inner
            = form_with url:root_path, method:"POST", class:"buy--content__inner__form", novalidate:"novalidate" do
              %ul.buy--content__inner__form__table
                %li.buy--content__inner__form__table__box
                  .buy--content__inner__form__table__box__pay 支払い金額
                  .buy--content__inner__form__table__box__price
                    %span ¥10,000
              %ul.buy--content__inner__form__accordion
                %li.buy--content__inner__form__accordion__parent
                  .buy--content__inner__form__accordion__parent__point
                    %input{name:"checkbox", type:"checkbox", value:"", disabled:"disabled"}
                    %i.buy--content__inner__form__accordion__parent__point__checkbox
                    %label ポイントを使用 (所持ポイント: P0)
              .buy--content
                .buy--content__inner
                  .buy--content__inner__clearfix
                    %h3.buy--content__inner__clearfix__left 支払い方法
                    = link_to "#", class:"buy--content__inner__clearfix__right" do
                      %span 変更する
                  %p.buy--content__inner__info
                    クレジットカード
                    %br
                      ****************
                    有効期限 00 / 00
                  .buy--content__inner__logo
                    = image_tag "pict/visa.svg",width:"65", height:"65",  alt:"visa"
              .buy--content
                .buy--content__inner
                  .buy--content__inner__clearfix
                    %h3.buy--content__inner__clearfix__left 配送先
                    = link_to "#", class:"buy--content__inner__clearfix__right" do
                      %span 変更する
                  %address.buy--content__inner__info
                    〒○○○-○○○○
                    %br
                      ○○○ ○○○ ○○○
                    ○○ ○○
              .buy--content
                %button{name:"button", type:"button", value:"", class:"buy--content__button"} 購入する
    = render "layouts/another-footer"

app/views/items/show.html.haml
.wrapper
  = render "header"
  .breadCrumbs
    .breadCrumb
      %li
        = link_to "FURIMA","#"
      %li
        %i.fa.fa-angle-right
      %li
        = link_to "ベビー・キッズ","#"
      %li
        %i.fa.fa-angle-right
      %li
        = link_to "ベビー服(男女兼用)  ~95cm","#"
      %li
        %i.fa.fa-angle-right
      %li
        = link_to "アウター","#"
      %li
        %i.fa.fa-angle-right
      %li
        %p product3
  .main-item-show
    .showMain
      .contentLeftpp
      .contentRightt
        .topContentt
          .itemBoxx
            %h2.itemBoxx__name
              = @item.name
            .itemBoxx__body
              %ul
                %li
                  =image_tag ("#{@item.item_images[0].image_url}"),class:"image"
                  - @item.item_images.each do |item|
                    =image_tag("#{item.image_url}",  height: '75', width: '75')
            .itemBoxx__price
              %span
                ¥
                =@item.price
              .priCe-Detail
                %span
                  (税込)
                %span
                  送料込み
            .itemDetail
              =@item.i_text
            .show-itemBtn
              - if user_signed_in? && current_user.id == @item.user_id
                .show-itemBtn_off
              - elsif user_signed_in?
                .show-itemBtn_on
                  =link_to "購入画面へ進む" ,purchase_path(@item.id)
              - else
                .show-itemBtn_off
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td
                      =@item.user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      = Category.find(@item.category_id).parent.parent.name
                      %br
                      = Category.find(@item.category_id).parent.name
                      %br
                      = Category.find(@item.category_id).name
                  %tr
                    %th ブランド
                    %td
                  %tr
                    %th 商品のサイズ
                    %td
                  %tr
                    %th 商品の状態
                    %td
                      =Itemcondition.find(@item.condition_id).value
                      
                  %tr
                    %th 配送料の負担
                    %td
                      =Deliveryfeeburgen.find(@item.shipping.fee_burgen_id).value
                  %tr
                    %th 配送方法
                    %td
                      =Deliveryservice.find(@item.shipping.service_id).value
                  %tr
                    %th 発送元の地域
                    %td
                      =link_to "#" do
                        =Deliveryarea.find(@item.shipping.area_id).name
                  %tr
                    %th 発送日の目安
                    %td 4-7日で発送
            .optionalArea
              - if user_signed_in? && current_user.id == @item.user_id
                .show-itemBtn
                  =link_to "編集する",edit_item_path(@item.id)
                  =link_to "削除する",item_path(@item.id), method: :delete
              - else user_signed_in? 
                .show-itemBtn_edit-off 
                %ul
                  %li#likeBtn.optionalBtn.likeBtn
                    %i.fa.fa-star
                    お気に入り 0
                %ul.optional
                  %li.optionalBtn
                    =link_to "#" do
                      %i.fa.fa-flag 不適切な商品の通報
          .commentBoxx
            %ul.commentContents
              %form#new_comment.new_comment{ action: "#",method: "post"}
                %input{name: "utf8", type: "hidden", value: "✓"}/
                %input{name:  "authenticity_token", type: "hidden", value: "UZaji94lj/rTfLW3DcSaCXs2HPv6Ic+zHxCyGaZhfKQcIpGKWGwWxX9gCQcYcZ2SdCqU5NyBOUL3tc3504qWYA=="}
                %textarea#comment_body{name: "comment[body]", required: "required"}
                %p.noticeMsg
                  相手のことを考え丁寧なコメントを心がけましょう。
                  %br/
                  不快な言葉遣いなどは利用制限や退会処分となることがあります。
                %br/
                %button.commentBtn-show{name: "button", type: "submit"}
                  %i.fa.fa-comment
                  コメントする
        %ul.linKs
          %li
            = link_to "#" do
              %i.fa.fa-angle-left
              %span
              前の商品
          %li
            =link_to "#" do
              %span 後ろの商品
              %i.fa.fa-angle-right
        .relatedItems
          =link_to "ベビー・キッズをもっと見る" ,"#"
          .productLists
  = render "footer"