config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users
  root 'items#index'
  
  resources :users , only:[:index] do
    collection do
      get :logout 
      get :creditcard
    end
  end

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get :purchase
    end
    collection do
      get :category
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"
  before_action :set_card, only:[:new, :delete, :show]

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    unless card.blank?
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end


  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
  
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
.wrapper
  = render "items/header"
  .main
    .content
      .content__left
        .content__left__mypage
          %h2.mypage-head 設定
          .content__left__mypage__list
            .content__left__mypage__list__item
              =link_to "クレジットカード登録", new_card_path, method: :get
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "ログアウト", logout_users_path, method: :get
      .content__right3
        .content__right3__card
          .content__right3__card__headcolor
            %h2.content__right3__card__headcolor__text クレジットカード情報入力
          .content__right3__card__registrationform
            = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class:"content__right3__card__registrationform__content") do
              .content__right3__card__registrationform__content__cardnumber
                %label カード番号
                = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
                %br
              .content__right3__card__registrationform__content__validexp
                %label 有効期限
                .content__right3__card__registrationform__content__selectwrap
                  %select#exp_month{name: "exp_month", type: "text", class:"content__right3__card__registrationform__content__validexp__selectwrap__exp"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %span 月/
                  %select#exp_year{name: "exp_year", type: "text", class:"content__right3__card__registrationform__content__validexp__selectwrap__exp"}
                    %option{value: ""} --
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %span 年
                %br
              .content__right3__card__registrationform__content__security
                %label セキュリティコード
                = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              .content__right3__card__registrationform__content__btn
                #card_token
                = submit_tag "登録する", id: "token_submit"

  =render "items/footer"

app/views/card/pay.html.haml
.wrapper
  = render "items/header"
  .main
    .content
      .content__left
        .content__left__mypage
          %h2.mypage-head 設定
          .content__left__mypage__list
            .content__left__mypage__list__item
              =link_to "クレジットカード登録", new_card_path, method: :get
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "ログアウト", logout_users_path, method: :get
      .content__right3
        .content__right3__card
          .content__right3__card__headcolor
            %h2.content__right3__card__headcolor__text クレジットカード情報入力
          .content__right3__card__registrationform
            = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              .content__right3__card__registrationform__content
                .content__right3__card__registrationform__content__formgroup1
                  = form.label :カード番号, class: 'payment_card_no'
                  %span.form-require 必須
                  = form.text_field :name, class: 'payment_card_no1', placeholder: '半角数字のみ'
                  %ul#card-no-error-wrapper.has-error-text
                  %ul.signup-card-list
                    %li
                    = image_tag "logo.png", height: "20px"
                    %li
                    = image_tag "logo.png", height: "20px"
                    %li
                    = image_tag "logo.png", height: "20px"
                .content__right3__card__registrationform__content__formgroup2
                  = form.label :有効期限, class: 'payment_card_no'
                  %span.form-require 必須
                  %br/
                  .select-wrap.half_box
                    .select-wrap.half
                      %select#payment_card_expire_mm.select-default
                        %option{value: "01"} 01
                        %option{value: "02"} 02
                        %option{value: "03"} 03
                        %option{value: "04"} 04
                        %option{value: "05"} 05
                        %option{value: "06"} 06
                        %option{value: "07"} 07
                        %option{value: "08"} 08
                        %option{value: "09"} 09
                        %option{value: "10"} 10
                        %option{value: "11"} 11
                        %option{value: "12"} 12
                      %i.icon-arrow-bottom
                      %span 月
                    .select-wrap.half
                      %select#payment_card_expire_yy.select-default
                        %option{value: "20"} 20
                        %option{value: "21"} 21
                        %option{value: "22"} 22
                        %option{value: "23"} 23
                        %option{value: "24"} 24
                        %option{value: "25"} 25
                        %option{value: "26"} 26
                        %option{value: "27"} 27
                        %option{value: "28"} 28
                        %option{value: "29"} 29
                        %option{value: "30"} 30
                      %i.icon-arrow-bottom
                      %span 年
                  %ul#expire-mm-error-wrapper.has-error-text
                  %ul#expire-yy-error-wrapper.has-error-text
                .content__right3__card__registrationform__content__formgroup3
                  = form.label :セキュリティコード, class: 'payment_card_no'
                  %span.form-require 必須
                  = form.text_field :name, class: 'payment_card_no3', placeholder: 'カード背面4桁もしくは3桁の番号'
                .content__right3__card__registrationform__content__formgroup4
                  = submit_tag "追加する", id: "token_submit"
  =render "items/footer"

app/views/card/show.html.haml
.wrapper
  = render "items/header"
  .main
    .content
      .content__left
        .content__left__mypage
          %h2.mypage-head 設定
          .content__left__mypage__list
            .content__left__mypage__list__item
              =link_to "クレジットカード登録", new_card_path, method: :get
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "サンプル", "#"
            .content__left__mypage__list__item
              =link_to "ログアウト", logout_users_path, method: :get
      .content__right4
        .content__right4__card
          .content__right4__card__headcolor
            %h2.content__right4__card__headcolor__text 登録クレジットカード情報
          .content__right4__card__info
            .content__right4__card__info__content
              .content__right4__card__info__content__formgroup1
              %label カード番号
              = "**** **** **** " + @default_card_information.last4
              %br
              %label 有効期限
              - exp_month = @default_card_information.exp_month.to_s 
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
              = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class:"btn") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button 削除する
        
  =render "items/footer"